# Generated by Django 2.2.28 on 2023-04-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_account_settings_bank_account_budget_reviews_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.TextField()),
            ],
        ),
    ]
