# Generated by Django 2.2.28 on 2023-04-03 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
