# Generated by Django 2.2.28 on 2023-04-03 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
