# Generated by Django 2.2.28 on 2023-04-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_delete_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('isactive', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Account_Settings',
        ),
    ]
