# Generated by Django 2.2.28 on 2023-04-03 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20230403_0103'),
        ('users', '0003_auto_20230402_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='setting_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_setting_id', to='home.Settings'),
        ),
    ]
